### ISSUE TITLE
Jonathan - Todo

### ISSUE THREAD

**Issue by KarstenRoemling** [KarstenRoemling/Paint-Program#1]
# Jonathan - Deine Aufgaben #1 (Startup)

- [x] GitHub verstehen
- [x] GitHub Desktop herunterladen
- [x] Die Interface Repository Clonen (File > Clone Repository) und mit BlueJ öffnen
- [x] Wenn du etwas veränderst (das funktioniert), die Branch dev auswählen und auf Fetch Origin klicken

# Jonathan - Deine Aufgaben #2 (Java AWT Surface)

- [x] Bearbeite die Surface Klasse, indem du
   - [x] die Buttons "decrease" und "increase" tauschst,
   - [x] den Button "subtrahieren" löscht,
   - [x] eine Überschrift als Label für die Auswahl des Werkzeugs (Pinsel, Linie, etc) hinzufügst (z.B. "Werkzeugauswahl"),
   - [x] nach dem Vorbild des Clear-Buttons einen ClickListener für die "increase"- und "decrease"-Buttons einfügst, der die Variable Manager.mode jeweils erhöht oder verkleinert und den Text des Labels "modeName" updatet,
    - [x] deine Änderungen mit GitHub Desktop *IN DIE DEV-BRANCH* commitest.

*Wenn du Fragen hast, hinterlasse einen Kommentar*

**Comment by CaptainGarry** [comment]
pervect
